In [112]:

file_path = 'msa_embeddings/A0A2G8PD13.t'  # Specify the path to your .t file
npz_file = torch.load(file_path)  # Load the .npz file
npz_file.size()

torch.Size([507])

In [70]:
import zipfile
import numpy as np
import pandas as pd
import os
import torch

In [117]:
with zipfile.ZipFile('msa_embeddings_full_60K.zip', 'r') as zip_ref:
    zip_ref.extractall()

In [72]:
seq_acc = pd.read_csv('/home/ubuntu/proteinbind/msa_accession.csv', header=None)
seq_acc.rename(columns={0: 'filename', 1: 'sequence'}, inplace=True)
seq_acc

         filename                                           sequence
0      A0A2S5WJA1  MLTHSPSVEARPNDPAPARAPADSQVEVNRIRESFERWQAELVSEA...
1      A0A1L3MDX2  MAGPQRRGGGAGGGEREGRRGGRGRRRRRDRRGGRRGAAEKSQYLE...
2      A0A1Q9T952  MDGATPSRVGRVAVVVAVLAAGCGWALVLRHGFPHGDDVLHAMAGQ...
3      A0A2X3ERZ6  MDHQLRRIHRETARVLRERLAPAVSRVVGAALTRHIDRRRPTPANA...
4      A0A2T0Y3U7  MRLTVIGCSGSFPGPGSPASCYLVQAEDGGRTWRVVLDLGSGALGA...
...           ...                                                ...
64070  A0A146UL17  RRRRRRAQGTKTHRRTGGAGSTAPETGTPAGRHSEEAGAIAVTAER...
64071  A0A0Q9RII2  MPPPSAWTDLVDEVGAAGDSTVLVSNEDFGRAHDYQAGRIVRELGQ...
64072  A0A0P6E9Z4  VEEQLTAQVIQLERVENQNKILMEEIASLNERRKTRVLDQANGISN...
64073  A0A087SKT0  MSRLPHLLVGTCLLALVGGAAVPPPATVLQLSDIHLSAPNSSGAWA...
64074  A0A0P5BCC1  MQHVCGPSLSVLKHSNTHSELATLLIETFLKLRQSSQPIVTESLHY...

[64075 rows x 2 columns]

In [119]:
dir_path = 'msa_embeddings/'
data = []

for filename in os.listdir(dir_path):
    try:
        # Load the numpy array
        array = torch.load(os.path.join(dir_path, filename))

        # Add the filename and array data to the list
        row = [filename] + array.tolist()
        data.append(row)
    except EOFError:
        print(f"Error loading file {filename}: EOFError (Ran out of input)")
    except Exception as e:
        print(f"Error loading file {filename}: {str(e)}")
        continue

Error loading file A0A165ZDN0.t: EOFError (Ran out of input)
Error loading file A0A2I0X9C3.t: EOFError (Ran out of input)
Error loading file A0A1M4ZAQ9.t: EOFError (Ran out of input)

In [122]:
# Create a DataFrame from the list
df = pd.DataFrame(data)

# Set the column names
df.columns = ['filename'] + ['col_{}'.format(i) for i in range(1, df.shape[1])]

In [123]:
# Print the DataFrame
df

,filename,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_1015,col_1016,col_1017,col_1018,col_1019,col_1020,col_1021,col_1022,col_1023,col_1024
0,A0A2G8PD13.t,-4.512762,-2.699844,-3.029103,-3.228155,-3.651123,-3.794067,-4.025218,-4.019146,-4.035903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A0A111V1H7.t,-5.541236,-3.113148,-3.309378,-3.376711,-3.463679,-3.475914,-3.480719,-3.436559,-3.476898,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A0A1I1Y7J0.t,-5.875367,-2.540716,-2.701454,-2.982790,-3.440745,-3.722954,-3.841881,-4.074691,-4.077506,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A0A0N4UB27.t,-5.117220,-3.436366,-3.771586,-3.785861,-3.698311,-3.670988,-3.753586,-3.924538,-3.989533,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A0A0H3DH39.t,-6.027295,-3.674835,-3.691297,-3.761550,-3.806380,-3.753679,-3.817455,-3.907805,-3.835502,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64067,A0A2K4AHP6.t,-6.044947,-3.680065,-4.079382,-4.343941,-4.022706,-4.015797,-4.356930,-4.454320,-3.917845,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64068,A0A1J4MJQ3.t,-4.401739,-1.952961,-2.073732,-2.058981,-2.064200,-2.122905,-2.082541,-2.056831,-2.119369,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64069,C3X3X5.t,-5.958816,-4.156373,-4.392713,-4.368334,-4.398526,-4.451797,-4.362889,-4.529393,-4.423726,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64070,A0A1M3LLG6.t,-5.558014,-3.411573,-3.755356,-3.675714,-3.739644,-3.719260,-3.758301,-3.793976,-3.791947,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64071,A0A2D6YJH4.t,-5.673605,-2.957412,-3.186747,-3.438176,-3.505425,-3.548855,-3.585058,-3.662465,-3.698595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
df['filename'] = df['filename'].str.replace('.t', '')

<ipython-input-130-210ac60708ea>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['filename'] = df['filename'].str.replace('.t', '')

In [131]:
merged_df = pd.merge(seq_acc, df, on='filename')

In [132]:
merged_df

,filename,sequence,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,...,col_1015,col_1016,col_1017,col_1018,col_1019,col_1020,col_1021,col_1022,col_1023,col_1024
0,A0A2S5WJA1,MLTHSPSVEARPNDPAPARAPADSQVEVNRIRESFERWQAELVSEA...,-5.811236,-2.593274,-2.532150,-2.594115,-2.597776,-2.655900,-2.605827,-2.697111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A0A1L3MDX2,MAGPQRRGGGAGGGEREGRRGGRGRRRRRDRRGGRRGAAEKSQYLE...,-4.777200,-2.419914,-2.422961,-2.472076,-2.473533,-2.455485,-2.383902,-2.423016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A0A1Q9T952,MDGATPSRVGRVAVVVAVLAAGCGWALVLRHGFPHGDDVLHAMAGQ...,-5.345448,-2.562079,-2.714391,-2.744930,-2.782492,-2.782822,-2.866978,-2.915249,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A0A2X3ERZ6,MDHQLRRIHRETARVLRERLAPAVSRVVGAALTRHIDRRRPTPANA...,-5.234344,-2.437364,-2.376390,-2.398602,-2.382477,-2.263439,-2.372267,-2.392478,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A0A2T0Y3U7,MRLTVIGCSGSFPGPGSPASCYLVQAEDGGRTWRVVLDLGSGALGA...,-5.828944,-3.756761,-3.972982,-4.069027,-3.934537,-4.055618,-4.148831,-3.805191,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64067,A0A146UL17,RRRRRRAQGTKTHRRTGGAGSTAPETGTPAGRHSEEAGAIAVTAER...,-4.331457,-2.316150,-2.142215,-2.097159,-2.076375,-2.084424,-2.110661,-2.106336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64068,A0A0Q9RII2,MPPPSAWTDLVDEVGAAGDSTVLVSNEDFGRAHDYQAGRIVRELGQ...,-5.368884,-2.825613,-3.361572,-3.576393,-3.716054,-3.895494,-3.861307,-3.743646,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64069,A0A0P6E9Z4,VEEQLTAQVIQLERVENQNKILMEEIASLNERRKTRVLDQANGISN...,-5.119342,-2.565385,-2.612941,-2.661251,-2.775269,-2.684798,-2.702091,-2.813425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64070,A0A087SKT0,MSRLPHLLVGTCLLALVGGAAVPPPATVLQLSDIHLSAPNSSGAWA...,-5.074806,-2.495255,-2.585902,-2.569676,-2.620098,-2.671610,-2.639417,-2.688915,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64071,A0A0P5BCC1,MQHVCGPSLSVLKHSNTHSELATLLIETFLKLRQSSQPIVTESLHY...,-4.796048,-3.225437,-3.200898,-3.190473,-3.326498,-2.992762,-3.091130,-3.365728,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [133]:
merged_df['sequence'].to_csv('aa_sequences.txt', index=False, header=False)

In [134]:
values = merged_df.drop(['sequence','filename'], axis=1)
values

,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,...,col_1015,col_1016,col_1017,col_1018,col_1019,col_1020,col_1021,col_1022,col_1023,col_1024
0,-5.811236,-2.593274,-2.532150,-2.594115,-2.597776,-2.655900,-2.605827,-2.697111,-2.683188,-2.652440,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-4.777200,-2.419914,-2.422961,-2.472076,-2.473533,-2.455485,-2.383902,-2.423016,-2.528197,-2.488107,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-5.345448,-2.562079,-2.714391,-2.744930,-2.782492,-2.782822,-2.866978,-2.915249,-3.134981,-3.207453,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-5.234344,-2.437364,-2.376390,-2.398602,-2.382477,-2.263439,-2.372267,-2.392478,-2.344610,-2.273724,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-5.828944,-3.756761,-3.972982,-4.069027,-3.934537,-4.055618,-4.148831,-3.805191,-3.940912,-3.967646,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64067,-4.331457,-2.316150,-2.142215,-2.097159,-2.076375,-2.084424,-2.110661,-2.106336,-2.124454,-2.131002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64068,-5.368884,-2.825613,-3.361572,-3.576393,-3.716054,-3.895494,-3.861307,-3.743646,-4.185288,-4.210293,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64069,-5.119342,-2.565385,-2.612941,-2.661251,-2.775269,-2.684798,-2.702091,-2.813425,-2.802537,-2.846341,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64070,-5.074806,-2.495255,-2.585902,-2.569676,-2.620098,-2.671610,-2.639417,-2.688915,-2.685717,-2.710342,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64071,-4.796048,-3.225437,-3.200898,-3.190473,-3.326498,-2.992762,-3.091130,-3.365728,-3.231341,-3.490717,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
tensor = torch.tensor(values.values)

In [136]:
torch.save(tensor, 'MSA_embeddings.pt')